{% set name = "dragonfly2" %}
{% set version = "0.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b85873f813491212ec246bbf1592e6cae4d466e9b5075124a9f240e704619aae


build:
  number: 0

requirements:
  host:
    - python
    - pip

  run:
    - python
    - setuptools >=40.0.0
    - packaging >=19.0
    - six
    - pyperclip >=1.7.0
    - enum34
    - regex
    - decorator
    - lark-parser
    - comtypes  # [win]
    - pywin32  # [win]
    - psutil >=5.5.1  # [linux]
    - pynput >=1.4.2  # [linux]
    - pynput >=1.4.2  # [osx]
    - pyobjc-core >=5.2  # [osx]
    - py-applescript  # [osx]
    - json-rpc
    - Werkzeug
    - requests

test:
  imports:
    - dragonfly

about:
  home: https://github.com/dictation-toolbox/dragonfly
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Dragonfly is a speech recognition framework for Python that makes it convenient to create custom commands to use with speech recognition software.
  description: |
    Dragonfly is a speech recognition framework for Python that makes it convenient to
    create custom commands to use with speech recognition software. It was written
    to make it very easy for Python macros, scripts, and applications to interface
    with speech recognition engines. Its design allows speech commands and grammar
    objects to be treated as first-class Python objects.
  doc_url: https://dragonfly2.readthedocs.io/en/latest/
  dev_url: https://github.com/dictation-toolbox/dragonfly

extra:
  recipe-maintainers:
    - ndmaxar
    - oblute
    - rluria14
