{% set name = "dragonfly2" %}
{% set version = "0.33.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce7cee8f787ab15f254df3364f0061f62e8431eeb36b471a0fc1bf6cced1c88c

build:
  number: 0

requirements:
  host:
    - python
    - pip

  run:
    - comtypes  # [win]
    - decorator
    - enum34  # [py<34]
    - json-rpc
    - lark-parser ==0.8.*
    - packaging >=19.0
    - psutil >=5.5.1  # [linux]
    - py-applescript >=1.0.0  # [osx]
    - pynput >=1.4.2  # [linux]
    - pyobjc-core >=5.2  # [osx]
    - pyperclip >=1.7.0
    - python
    - pywin32  # [win]
    - regex
    - requests
    - setuptools >=40.0.0
    - six
    - werkzeug

test:
  imports:
    - dragonfly
    - dragonfly.accessibility

about:
  home: https://github.com/dictation-toolbox/dragonfly
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Dragonfly is a speech recognition framework for Python that makes it convenient to create custom commands to use with speech recognition software.
  description: |
    Dragonfly is a speech recognition framework for Python that makes it convenient to
    create custom commands to use with speech recognition software. It was written
    to make it very easy for Python macros, scripts, and applications to interface
    with speech recognition engines. Its design allows speech commands and grammar
    objects to be treated as first-class Python objects.
  doc_url: https://dragonfly2.readthedocs.io/en/latest/
  dev_url: https://github.com/dictation-toolbox/dragonfly

extra:
  recipe-maintainers:
    - mxr-conda
